targets:
  graphlink:
    builders:
      graphlink|graphlinkGeneratorBuilder:
        enabled: true
        generate_for:
          include:
            - lib/**/*.graphql
        options:
          Long: int
          ID: int

builders:
  graphlinkGeneratorBuilder:
    import: 'package:graphlink/code_generators.dart'
    builder_factories: ['graphlinkGeneratorBuilder']
    build_extensions:
      .graphql:
        - .gq.dart
    build_to: source
    auto_apply: dependents
