name: graphlink
description: |
  GraphLink is a powerful code generation tool that generates type-safe client and server code from GraphQL schemas for Dart, Java, Spring Boot and more.
version: 4.5.3
homepage: https://graphlink.dev
repository: https://github.com/Oualitsen/graphlink
documentation: https://graphlink.dev/docs/index.html

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  source_gen: ^1.5.0
  glob: ^2.1.2
  logger: ^2.5.0
  build: ^2.4.1
  yaml: ^3.1.3
  args: ^2.7.0

dev_dependencies:
  test:
  flutter_lints: ^3.0.1
  build_runner: 
