import 'package:graphlink/src/extensions.dart';
import 'package:graphlink/src/model/gl_query_element.dart';
import 'package:graphlink/src/model/new_parser/gl_parser.dart';
import 'package:graphlink/src/model/built_in_dirctive_definitions.dart';
import 'package:graphlink/src/model/gl_directive.dart';
import 'package:graphlink/src/model/gl_argument.dart';
import 'package:graphlink/src/model/gl_field.dart';
import 'package:graphlink/src/model/gl_fragment.dart';
import 'package:graphlink/src/exceptions/parse_exception.dart';
import 'package:graphlink/src/model/gl_directives_mixin.dart';
import 'package:graphlink/src/model/gl_token.dart';
import 'package:graphlink/src/model/gl_type.dart';
import 'package:graphlink/src/model/gl_type_definition.dart';
import 'package:graphlink/src/utils.dart';

enum GLQueryType { query, mutation, subscription }

/// Composite key for the [GLParser.queries] map. An operation is uniquely
/// identified by its field name *and* its operation type — a query and a
/// mutation may legitimately share the same name (e.g. `transfer` as both a
/// lookup query and an initiating mutation), so the field name alone is not a
/// unique key.
class GLOperationKey {
  final String fieldName;
  final GLQueryType type;

  const GLOperationKey(this.fieldName, this.type);

  GLOperationKey.of(GLQueryDefinition definition)
      : fieldName = definition.token,
        type = definition.type;

  @override
  bool operator ==(Object other) =>
      other is GLOperationKey &&
      other.fieldName == fieldName &&
      other.type == type;

  @override
  int get hashCode => Object.hash(fieldName, type);

  @override
  String toString() => '$fieldName(${type.name})';
}

class GLQueryDefinition extends GLToken with GLDirectivesMixin {
  /// Operation variables keyed by their `$`-token, preserving declaration order
  /// (Dart `Map` literals/insertion preserve order). Kept private so lookups go
  /// through [getArgumentByName] in O(1) instead of a linear scan — the
  /// auto-generated all-fields walk merges variables millions of times.
  final Map<String, GLArgumentDefinition> _arguments;

  /// All operation variables in declaration order. Returns a fresh list, so
  /// callers must mutate via [setArgument], not the returned list.
  List<GLArgumentDefinition> get arguments => _arguments.values.toList();

  /// O(1) lookup of an operation variable by its `$`-token, or null if absent.
  GLArgumentDefinition? getArgumentByName(String name) => _arguments[name];

  /// Inserts [arg] (or replaces the existing one with the same token, keeping
  /// its declaration position).
  void setArgument(GLArgumentDefinition arg) => _arguments[arg.token] = arg;

  /// Drops the operation variable with [token], if present. Used by the
  /// hoist-args pass to pull propagated args out before replacing them with a
  /// single synthesized `<Op>FieldArgs` object argument.
  void removeArgument(String token) => _arguments.remove(token);

  final List<GLQueryElement> elements;
  final GLQueryType type; //query|mutation|subscription
  Set<GLFragmentDefinitionBase>? _allFrags;

  /// Target-language-safe identifier for the generated client method name.
  /// Defaults to the wire [token]; overwritten by the keyword pass when the
  /// operation name collides with a reserved word (e.g. `return` → `return_`).
  /// The wire/operation name (query text, `operationName`) always uses [token].
  String? _codeName;
  String get codeName => _codeName ?? token;
  set codeName(String value) => _codeName = value;

  GLTypeDefinition? _glTypeDefinition;
  GLTypeDefinition? _glFullResponse;

  Set<String> get fragmentNames {
    return elements.expand((e) => e.fragmentNames).toSet();
  }

  Set<GLFragmentDefinitionBase> fragments(GLParser g) {
    if (_allFrags == null) {
      var frags = fragmentNames
          .map((e) => g.getFragmentByName(e))
          .where((e) => e != null)
          .map((e) => e!)
          .toSet();
      _allFrags = {...frags, ...frags.expand((e) => e.dependecies)};
    }
    return _allFrags!;
  }

  /// True when this operation was auto-generated by `_generateForField` from an
  /// all-fields fragment walk. False for hand-written operations. Used only to
  /// gate the `autoQueryArgumentLimit` skip cap — hand-written queries are never
  /// pruned regardless of their propagated-arg count.
  bool isAutoGenerated = false;

  GLQueryDefinition(super.tokenInfo, List<GLDirectiveValue> directives,
      List<GLArgumentDefinition> arguments, this.elements, this.type)
      : _arguments = {for (final a in arguments) a.token: a} {
    directives.forEach(addDirective);
    checkVariables();
  }

  void checkVariables() {
    for (var elem in elements) {
      checkElement(elem);
    }
  }

  void checkElement(GLQueryElement element) {
    var list = element.arguments;

    for (var arg in list) {
      if ("${arg.value}".startsWith("\$")) {
        var check = checkValue("${arg.value}");
        if (!check) {
          throw ParseException("Argument ${arg.value} was not declared",
              info: arg.tokenInfo);
        }
      }
    }
  }

  bool checkValue(String value) {
    return _arguments.containsKey(value);
  }

  GLTypeDefinition getFullResponseTypeDefinition(GLParser parser) {
    var result = _glFullResponse;
    if(result == null) {
      final errorsType = GLListType(GLType(parser.getTypeByName('GraphLinkError')!.tokenInfo, false), true);
      final dataType = GLType(getGeneratedTypeDefinition().tokenInfo, true);
      result = _glFullResponse = GLTypeDefinition(name: tokenInfo.ofNewName(_fullResponseName()), nameDeclared: false, fields: [
        GLField(name: "errors".toToken(), type: errorsType, arguments: [], directives: []),
        GLField(name: "data".toToken(), type: dataType, arguments: [], directives: []),
      ], interfaceNames: {}, directives: [], derivedFromType: null, extension: false, isResponseType: true);
      result.addInterface(parser.interfaces["GraphLinkFullResponse"]!);
      result.addDirective(
          GLDirectiveValue(glInternal.toToken(), [], [], generated: true));
    }
    return result;
  }

  GLTypeDefinition getGeneratedTypeDefinition() {
    var gqDef = _glTypeDefinition;
    if (gqDef == null) {
      _glTypeDefinition = gqDef = GLTypeDefinition(
        name: tokenInfo.ofNewName(_getGeneratedTypeName()),
        nameDeclared: getNameValueFromDirectives(getDirectives()) != null,
        fields: _generateFields(),
        directives: getDirectives(),
        interfaceNames: {},
        derivedFromType: null,
        extension: false,
        isResponseType: true,
      );
      gqDef.addDirective(
          GLDirectiveValue(glInternal.toToken(), [], [], generated: true));
    }
    return gqDef;
  }

  void updateTypeDefinition(GLTypeDefinition def) {
    _glTypeDefinition = def;
  }

  GLTypeDefinition? get typeDefinition => _glTypeDefinition;

  /// True when the user pinned the response type name via a directive
  /// (e.g. `@glName`). When true, auto collision-disambiguation is skipped and
  /// the explicit name is honoured as-is.
  bool get hasDeclaredResponseName =>
      getNameValueFromDirectives(getDirectives()) != null;

  String? _generatedNameStem;

  /// Overrides the auto-derived `<Field>` stem used to build both the
  /// `<stem>Response` and `<stem>FullResponse` type names. Used by the
  /// projection pass to disambiguate auto-generated wrapper names that would
  /// otherwise collide with a user-declared type. Must be called before
  /// [getGeneratedTypeDefinition] / [getFullResponseTypeDefinition] are first
  /// accessed (the type definitions are cached on first build).
  void overrideGeneratedNameStem(String stem) {
    assert(_glTypeDefinition == null && _glFullResponse == null,
        'response type definition already built; stem override is too late');
    _generatedNameStem = stem;
  }

  /// The `<Field>`-style stem the generated wrapper names are built from.
  String get defaultGeneratedNameStem => tokenInfo.token.firstUp;

  String _getGeneratedTypeName() {
    return getNameValueFromDirectives(getDirectives()) ??
        "${_generatedNameStem ?? defaultGeneratedNameStem}Response";
  }

  String _fullResponseName() =>
      "${_generatedNameStem ?? defaultGeneratedNameStem}FullResponse";

  List<GLField> _generateFields() {
    return elements
        .map(
          (e) => GLField(
            name: e.alias ?? e.tokenInfo,
            type: e.returnProjectedType,
            arguments: [],
            directives: e.getDirectives(),
          ),
        )
        .toList();
  }

  GLArgumentDefinition findByName(String name) => _arguments[name]!;

  void applyDefaultCache(int defaultTTL) {
    if (type != GLQueryType.query) {
      throw ParseException("You cannot apply cache to ${type}",
          info: tokenInfo);
    }
    if (!hasDirective(glCache) && !hasDirective(glNoCache)) {
      addDirective(GLDirectiveValue.createDefaultCacheDirectiveValue(
          tokenInfo, defaultTTL));
    }
    for (final element in elements) {
      element.applyDefaultCache(defaultTTL);
    }
  }

  int get cacheTTL {
    var cache = getDirectiveByName(glCache);
    if (cache == null) {
      return 0;
    }
    return cache.getArgValue(glCacheTTL) as int? ?? 0;
  }

  List<String> get cacheTags {
    var cache = getDirectiveByName(glCache);
    if (cache == null) {
      return [];
    }
    return (cache.getArgValue(glCacheTagList) as List? ?? []).cast<String>();
  }

  List<String> get invalidateCacheTags {
    var cacheDir = getDirectiveByName(glCacheInvalidate);
    if (cacheDir == null) {
      return [];
    }
    return (cacheDir.getArgValue(glCacheTagList) as List? ?? []).cast<String>();
  }

  bool get cacheInvalidateAll {
    var cache = getDirectiveByName(glCacheInvalidate);
    if (cache == null) {
      return false;
    }
    return cache.getArgValueAsBool(glCacheArgAll);
  }
}
