// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by GraphLink dev
// GitHub: https://github.com/Oualitsen/graphlink
// Site: https://graphlink.dev
// Pub.dev https://pub.dev/packages/graphlink

declare module '../generated/context.js' {
  interface GraphLinkContext {
    // Set by InterceptorImpl.runBefore, read back by GreetingServiceImpl —
    // proves the interceptor actually ran, purely through response data.
    marker?: string;
  }
}

