query getAuthorWithoutArticle($id: ID!) {
  getAuthor(id: $id) {
    id
    name
  }
}

query getAuthorAndArticle($authorId: ID!, $articleId: ID!, $limit: Int!) {
  author: getAuthor(id: $authorId) {
    ... _all_fields
  }
  article: getArticle(id: $articleId) {
    ... _all_fields
  }
}
