import 'package:graphlink/src/model/built_in_dirctive_definitions.dart';

const glApplyOnServer = "applyOnServer";
const glApplyOnClient = "applyOnClient";

const fileHeadComment = """
// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by GraphLink
// GitHub: https://github.com/Oualitsen/graphlink
// Pub.dev https://pub.dev/packages/graphlink
// ignore_for_file: camel_case_types, constant_identifier_names, unused_import, non_constant_identifier_names
""";

const graphqlHeadComment = """
# GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
# Generated by Retrofit Graphql For Dart
# GitHub: https://github.com/Oualitsen/retrofit-Graphql-For-Dart/
# Pub.dev https://pub.dev/packages/graphlink
""";

const clientTypes = {
  'GraphLinkPayload',
  'GraphLinkError',
  'GraphLinkErrorLocation',
  'GraphLinkSubscriptionPayload',
  'GraphLinkSubscriptionErrorMessage',
  'GraphLinkSubscriptionMessage'
};
const clientInterfaces = {
  'GraphLinkSubscriptionErrorMessageBase',
  'GraphLinkGraphLinkWebSocketAdapter'
};

const javaClientAdapterNoParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!): String!
}
''';

const javaClientAdapterWithParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!, operationName: String!): String!
}
''';

const javaJsonEncoderDecorder = '''
  scalar gqlJavaMap ${glExternal}(glClass: "Map<String, Object>", ${glImport}: "${JavaImports.map}")
  scalar gqlJavaObject ${glExternal}(glClass: "Object")

  interface GraphLinkJsonEncoder
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
    encode(json: gqlJavaObject!): String!
  }

  interface GraphLinkJsonDecoder 
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
     decode(json: String!): gqlJavaMap!
  }

''';

const javaGraphLinkWebSocketAdapter = '''
scalar void ${glExternal}(glClass: "void")
scalar Consumer ${glExternal}(glClass: "Consumer<String>", glImport: "java.util.function.Consumer")
scalar VoidConsumer ${glExternal}(glClass: "Consumer<Void>", glImport: "java.util.function.Consumer")
scalar ThrowableConsumer ${glExternal}(glClass: "Consumer<Throwable>", glImport: "java.util.function.Consumer")
scalar GraphLinkException ${glExternal}(glClass: "GraphLinkException")

interface GraphLinkGraphLinkWebSocketAdapter ${glInterfaceFieldAsProperties} ${glInternal} {
   connect(onConnect: VoidConsumer!, onFailure: ThrowableConsumer): void!
   onMessage(message: Consumer!): void!
   sendMessage(message: String!): void!
   close: void!
}
''';

String getClientObjects([String lang = 'Dart']) {
  String dynamicValue = "dynamic";
  if (lang == "Java") {
    dynamicValue = "Object";
  }
  return '''
scalar gqlMapStrObj ${glExternal}(glClass: "Map<String, ${dynamicValue}>")
scalar dynamicValue ${glExternal}(glClass: "${dynamicValue}")


type GraphLinkPayload ${glInternal} {
  query: String!
  operationName: String!
  variables: gqlMapStrObj!
}

type GraphLinkError ${glInternal} {
  message: String!
  path: [dynamicValue!]
  extensions: gqlMapStrObj
  locations: [GraphLinkErrorLocation!]
}

type GraphLinkErrorLocation ${glInternal} {
  line: Int!
  column: Int!
}

type GraphLinkSubscriptionPayload ${glInternal} {
  query: String
  operationName: String
  variables: gqlMapStrObj
  data: gqlMapStrObj
}


interface GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  type: String
  id: String
}

type GraphLinkSubscriptionErrorMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: [GraphLinkError!]
}

type GraphLinkSubscriptionMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: GraphLinkSubscriptionPayload
}

enum GraphLinkAckStatus {none progress acknoledged }

''';
}

class JavaImports {
  static const map = "java.util.Map";
  static const hashMap = "java.util.HashMap";
  static const optional = "java.util.Optional";
  static const mono = "reactor.core.publisher.Mono";
  static const flux = "reactor.core.publisher.Flux";
  static const stream = "java.util.stream.Stream";
  static const collectors = "java.util.stream.Collectors";
  static const objects = "java.util.Objects";
  static const list = "java.util.List";
  static const arrayList = "java.util.ArrayList";
  static const arrays = "java.util.Arrays";
  static const collections = "java.util.Collections";
  static const uuid = "java.util.UUID";
  static const concurrentHashMap = "java.util.concurrent.ConcurrentHashMap";
  static const reentrantLock = "java.util.concurrent.locks.ReentrantLock";
  static const treeMap = "java.util.TreeMap";
  static const function = "java.util.function.Function";
  static const set = "java.util.Set";
  static const hashSet = "java.util.HashSet";
}

class SpringImports {
  static const controller = "org.springframework.stereotype.Controller";
  static const gqlArgument =
      "org.springframework.graphql.data.method.annotation.Argument";
  static const gqlDataFetchingEnvironment =
      "graphql.schema.DataFetchingEnvironment";
  static const gqlGraphQLException = "graphql.GraphQLException";
  static const repository = "org.springframework.stereotype.Repository";
  static const jpaRepository =
      "org.springframework.data.jpa.repository.JpaRepository";
  static const batchMapping =
      "org.springframework.graphql.data.method.annotation.BatchMapping";
  static const schemaMapping =
      "org.springframework.graphql.data.method.annotation.SchemaMapping";
  static const queryMapping =
      "org.springframework.graphql.data.method.annotation.QueryMapping";
  static const mutationMapping =
      "org.springframework.graphql.data.method.annotation.MutationMapping";
  static const subscriptionMapping =
      "org.springframework.graphql.data.method.annotation.SubscriptionMapping";
}
