import 'package:graphlink/src/model/built_in_dirctive_definitions.dart';

const glApplyOnServer = "applyOnServer";
const glApplyOnClient = "applyOnClient";

const fileHeadComment = """
// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by GraphLink
// GitHub: https://github.com/Oualitsen/graphlink
// Site: https://graphlink.dev
// Pub.dev https://pub.dev/packages/graphlink
// ignore_for_file: use_rethrow_when_possible camel_case_types, constant_identifier_names, unused_import, non_constant_identifier_names
""";

const graphqlHeadComment = """
# GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
# Generated by Retrofit Graphql For Dart
# GitHub: https://github.com/Oualitsen/retrofit-Graphql-For-Dart/
# Site: https://graphlink.dev
# Pub.dev https://pub.dev/packages/graphlink
""";
const javaCollectorsToList = "collect(Collectors.toList())";

const clientTypes = {
  'GraphLinkPayload',
  'GraphLinkError',
  'GraphLinkErrorLocation',
  'GraphLinkSubscriptionPayload',
  'GraphLinkSubscriptionErrorMessage',
  'GraphLinkSubscriptionMessage'
};
const clientInterfaces = {
  'GraphLinkSubscriptionErrorMessageBase',
};

const javaClientAdapterNoParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!): String!
}
''';

const javaClientAdapterWithParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!, operationName: String!): String!
}
''';

const javaJsonEncoderDecorder = '''
  scalar gqlJavaMap ${glExternal}(glClass: "Map<String, Object>", ${glImport}: "${JavaImports.map}")
  scalar gqlJavaObject ${glExternal}(glClass: "Object")

  interface GraphLinkJsonEncoder
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
    encode(json: gqlJavaObject!): String!
  }

  interface GraphLinkJsonDecoder 
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
     decode(json: String!): gqlJavaMap!
  }

''';

const javaGraphLinkWebSocketAdapter = '''
scalar void ${glExternal}(glClass: "void")
scalar Consumer ${glExternal}(glClass: "Consumer<String>", glImport: "java.util.function.Consumer")
scalar VoidConsumer ${glExternal}(glClass: "Consumer<Void>", glImport: "java.util.function.Consumer")
scalar ThrowableConsumer ${glExternal}(glClass: "Consumer<Throwable>", glImport: "java.util.function.Consumer")
scalar GraphLinkException ${glExternal}(glClass: "GraphLinkException")
''';

const javaWebSocketAdapter = '''
import java.util.Map;
import java.util.function.Consumer;

public interface GraphLinkWebSocketAdapter {

   void connect(Runnable onConnect, Consumer<Throwable> onFailure);

   void setMessageListener(Consumer<String> listener);

   void sendMessage(String message);

   void close();

   // Override to pass auth token or any connection metadata sent in connection_init
   default Map<String, Object> connectionInitPayload() { return null; }

   // Fires after a successful reconnect; used by the handler to re-subscribe
   default void setReconnectListener(Runnable onReconnect) {}
}
''';

String getClientObjects([String lang = 'Dart']) {
  String dynamicValue = "dynamic";
  if (lang == "Java") {
    dynamicValue = "Object";
  }
  return '''
scalar gqlMapStrObj ${glExternal}(glClass: "Map<String, ${dynamicValue}>")
scalar dynamicValue ${glExternal}(glClass: "${dynamicValue}")


type GraphLinkPayload ${glInternal} {
  query: String!
  operationName: String!
  variables: gqlMapStrObj!
}

type GraphLinkError ${glInternal} {
  message: String!
  path: [dynamicValue!]
  extensions: gqlMapStrObj
  locations: [GraphLinkErrorLocation!]
}

type GraphLinkErrorLocation ${glInternal} {
  line: Int!
  column: Int!
}

type GraphLinkSubscriptionPayload ${glInternal} {
  query: String
  operationName: String
  variables: gqlMapStrObj
  data: gqlMapStrObj
}


interface GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  type: String
  id: String
}

type GraphLinkSubscriptionErrorMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: [GraphLinkError!]
}

type GraphLinkSubscriptionMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: GraphLinkSubscriptionPayload
}

enum GraphLinkAckStatus {none progress acknoledged }

''';
}

/// Content of the generated `graph_link_uploads.dart` file.
/// Imported by both the client and adapter files — no circular dependency.
const dartUploadsFile = """
import 'dart:async';
import 'dart:typed_data';

typedef UploadProgressCallback = void Function(int sent, int total);
typedef GLUploadConverter = Object Function(GLUpload upload);
typedef GLMultipartAdapter = Future<String> Function(
    Map<String, Object> parts, UploadProgressCallback? onProgress);

class GLUpload {
  final Stream<List<int>> stream;
  final int? length;
  final String? filename;
  final String mimeType;

  GLUpload({
    required this.stream,
    this.length,
    this.filename,
    this.mimeType = 'application/octet-stream',
  });

  factory GLUpload.fromBytes(
    Uint8List bytes, {
    String? filename,
    String mimeType = 'application/octet-stream',
  }) {
    return GLUpload(
      stream: Stream.value(bytes),
      length: bytes.length,
      filename: filename,
      mimeType: mimeType,
    );
  }
}
""";

/// Emitted once in the client file — the default identity converter.
const dartUploadDefaultConverter = '''
/// Default converter — passes GLUpload through as-is.
/// The selected adapter's multipartCall handles GLUpload natively.
Object _defaultUploadConverter(GLUpload upload) => upload;
''';

const javaUploadProgressCallback = '''
@FunctionalInterface
public interface UploadProgressCallback {
    void onProgress(long sent, long total);
}
''';

const javaGraphLinkMultipartAdapter = '''
public interface GraphLinkMultipartAdapter {
    String executeMultipart(String operations, String mapJson, Map<String, GLUpload> files, UploadProgressCallback onProgress) throws java.io.IOException;

    default String executeMultipart(String operations, String mapJson, Map<String, GLUpload> files) throws java.io.IOException {
        return executeMultipart(operations, mapJson, files, null);
    }
}
''';

const javaGLUpload = '''
public final class GLUpload {

    private final InputStream stream;
    private final long length;
    private final String filename;
    private final String mimeType;

    public GLUpload(InputStream stream, long length, String filename, String mimeType) {
        this.stream = stream;
        this.length = length;
        this.filename = filename;
        this.mimeType = mimeType;
    }

    public GLUpload(InputStream stream, long length, String filename) {
        this(stream, length, filename, "application/octet-stream");
    }

    public static GLUpload fromBytes(byte[] bytes, String filename, String mimeType) {
        return new GLUpload(new ByteArrayInputStream(bytes), bytes.length, filename, mimeType);
    }

    public static GLUpload fromBytes(byte[] bytes, String filename) {
        return fromBytes(bytes, filename, "application/octet-stream");
    }

    public static GLUpload fromFile(File file) throws IOException {
        return new GLUpload(new FileInputStream(file), file.length(), file.getName(), "application/octet-stream");
    }

    public static GLUpload fromFile(File file, String mimeType) throws IOException {
        return new GLUpload(new FileInputStream(file), file.length(), file.getName(), mimeType);
    }

    public InputStream getStream() { return stream; }
    public long getLength() { return length; }
    public String getFilename() { return filename; }
    public String getMimeType() { return mimeType; }
}
''';

class JavaImports {
  static const map = "java.util.Map";
  static const hashMap = "java.util.HashMap";
  static const optional = "java.util.Optional";
  static const mono = "reactor.core.publisher.Mono";
  static const flux = "reactor.core.publisher.Flux";
  static const stream = "java.util.stream.Stream";
  static const collectors = "java.util.stream.Collectors";
  static const objects = "java.util.Objects";
  static const list = "java.util.List";
  static const arrayList = "java.util.ArrayList";
  static const arrays = "java.util.Arrays";
  static const collections = "java.util.Collections";
  static const uuid = "java.util.UUID";
  static const concurrentHashMap = "java.util.concurrent.ConcurrentHashMap";
  static const reentrantLock = "java.util.concurrent.locks.ReentrantLock";
  static const treeMap = "java.util.TreeMap";
  static const function = "java.util.function.Function";
  static const supplier = "java.util.function.Supplier";
  static const consumer = "java.util.function.Consumer";
  static const set = "java.util.Set";
  static const hashSet = "java.util.HashSet";
  static const inputStream = "java.io.InputStream";
  static const byteArrayInputStream = "java.io.ByteArrayInputStream";
  static const fileInputStream = "java.io.FileInputStream";
  static const file = "java.io.File";
  static const ioException = "java.io.IOException";
  static const linkedHashMap = "java.util.LinkedHashMap";
  static const completableFuture = "java.util.concurrent.CompletableFuture";
  static const securityContext = "org.springframework.security.core.context.SecurityContext";
  static const securityContextHolder = "org.springframework.security.core.context.SecurityContextHolder";
}

class SpringImports {
  static const controller = "org.springframework.stereotype.Controller";
  static const gqlArgument =
      "org.springframework.graphql.data.method.annotation.Argument";
  static const gqlDataFetchingEnvironment =
      "graphql.schema.DataFetchingEnvironment";
  static const gqlGraphQLException = "graphql.GraphQLException";
  static const repository = "org.springframework.stereotype.Repository";
  static const jpaRepository =
      "org.springframework.data.jpa.repository.JpaRepository";
  static const batchMapping =
      "org.springframework.graphql.data.method.annotation.BatchMapping";
  static const schemaMapping =
      "org.springframework.graphql.data.method.annotation.SchemaMapping";
  static const queryMapping =
      "org.springframework.graphql.data.method.annotation.QueryMapping";
  static const mutationMapping =
      "org.springframework.graphql.data.method.annotation.MutationMapping";
  static const subscriptionMapping =
      "org.springframework.graphql.data.method.annotation.SubscriptionMapping";
  static const multipartFile =
      "org.springframework.web.multipart.MultipartFile";
  static const filePart =
      "org.springframework.http.codec.multipart.FilePart";
}
