import 'package:graphlink/src/model/built_in_dirctive_definitions.dart';
import 'package:graphlink/src/serializers/java_imports.dart';

const glApplyOnServer = "applyOnServer";
const glApplyOnClient = "applyOnClient";

const glVersion = String.fromEnvironment('version', defaultValue: 'dev');

const fileHeadComment = """
// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by GraphLink $glVersion
// GitHub: https://github.com/Oualitsen/graphlink
// Site: https://graphlink.dev
// Pub.dev https://pub.dev/packages/graphlink
""";

const dartIgnoreForFile = "";
  //  "// ignore_for_file: use_rethrow_when_possible, camel_case_types, constant_identifier_names, unused_import, non_constant_identifier_names, no_leading_underscores_for_local_identifiers, unused_local_variable, annotate_overrides, library_private_types_in_public_api";

const graphqlHeadComment = """
# GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
# Generated by GraphLink $glVersion
# GitHub: https://github.com/Oualitsen/graphlink
# Site: https://graphlink.dev
# Pub.dev https://pub.dev/packages/graphlink
""";
const javaCollectorsToList = "collect(Collectors.toList())";

const clientTypes = {
  'GraphLinkPayload',
  'GraphLinkError',
  'GraphLinkErrorLocation',
  'GraphLinkSubscriptionPayload',
  'GraphLinkSubscriptionErrorMessage',
  'GraphLinkSubscriptionMessage'
};
const clientInterfaces = {
  'GraphLinkSubscriptionErrorMessageBase',
  'GraphLinkFullResponse',
};

const javaClientAdapterNoParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!): String!
}
''';

const javaClientAdapterWithParamSync = '''
interface GraphLinkClientAdapter 
${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!, operationName: String!): String!
}
''';

const javaJsonEncoderDecorder = '''
  scalar gqlJavaMap ${glExternal}(glClass: "Map<String, Object>", ${glImport}: "${JavaImports.map}")
  scalar gqlJavaObject ${glExternal}(glClass: "Object")

  interface GraphLinkJsonEncoder
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
    encode(json: gqlJavaObject!): String!
  }

  interface GraphLinkJsonDecoder
  ${glDecorators}(${glDecoratorsArgumentName}: ["@FunctionalInterface"], ${glApplyOnClient}: true, ${glApplyOnServer}: false)
   ${glInterfaceFieldAsProperties} ${glInternal} {
     decode(json: String!): gqlJavaMap!
  }

''';

const kotlinJsonEncoderDecoder = '''
  scalar gqlKotlinMap ${glExternal}(glClass: "Map<String, Any?>")
  scalar gqlKotlinAny ${glExternal}(glClass: "Any?")

  interface GraphLinkJsonEncoder
  ${glInterfaceFieldAsProperties} ${glInternal} {
    encode(json: gqlKotlinAny!): String!
  }

  interface GraphLinkJsonDecoder
  ${glInterfaceFieldAsProperties} ${glInternal} {
    decode(json: String!): gqlKotlinMap!
  }

''';

const kotlinClientAdapterGql = '''
  interface GraphLinkClientAdapter ${glInterfaceFieldAsProperties} ${glInternal} {
    execute(payload: String!): String!
  }
''';

const javaGraphLinkWebSocketAdapter = '''
scalar void ${glExternal}(glClass: "void")
scalar Consumer ${glExternal}(glClass: "Consumer<String>", glImport: "java.util.function.Consumer")
scalar VoidConsumer ${glExternal}(glClass: "Consumer<Void>", glImport: "java.util.function.Consumer")
scalar ThrowableConsumer ${glExternal}(glClass: "Consumer<Throwable>", glImport: "java.util.function.Consumer")
scalar GraphLinkException ${glExternal}(glClass: "GraphLinkException")
''';

const javaWebSocketAdapter = '''
import java.util.Map;
import java.util.function.Consumer;

public interface GraphLinkWebSocketAdapter {

   void connect(Runnable onConnect, Consumer<Throwable> onFailure);

   void setMessageListener(Consumer<String> listener);

   void sendMessage(String message);

   void close();

   // Override to pass auth token or any connection metadata sent in connection_init
   default Map<String, Object> connectionInitPayload() { return null; }

   // Fires after a successful reconnect; used by the handler to re-subscribe
   default void setReconnectListener(Runnable onReconnect) {}
}
''';

const clientObjects = '''
scalar gqlMapStrObj
scalar dynamicValue


type GraphLinkPayload ${glInternal} {
  query: String!
  operationName: String!
  variables: gqlMapStrObj!
}

type GraphLinkError ${glInternal} {
  message: String!
  path: [dynamicValue!]
  extensions: gqlMapStrObj
  locations: [GraphLinkErrorLocation!]
}

type GraphLinkErrorLocation ${glInternal} {
  line: Int!
  column: Int!
}

type GraphLinkSubscriptionPayload ${glInternal} {
  query: String
  operationName: String
  variables: gqlMapStrObj
  data: gqlMapStrObj
}


interface GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  type: String
  id: String
}

interface GraphLinkFullResponse ${glInternal} {
  errors: [GraphLinkError!]
}

type GraphLinkSubscriptionErrorMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: [GraphLinkError!]
}

type GraphLinkSubscriptionMessage implements GraphLinkSubscriptionErrorMessageBase ${glInternal} {
  id: String
  type: String
  payload: GraphLinkSubscriptionPayload
}

enum GraphLinkAckStatus {none progress acknoledged }

''';

/// Content of the generated `graph_link_uploads.dart` file.
/// Imported by both the client and adapter files — no circular dependency.
const dartUploadsFile = """
import 'dart:async';
import 'dart:typed_data';

typedef UploadProgressCallback = void Function(int sent, int total);
typedef GLUploadConverter = Object Function(GLUpload upload);
typedef GLMultipartAdapter = Future<String> Function(
    Map<String, Object> parts, UploadProgressCallback? onProgress);

class GLUpload {
  final Stream<List<int>> stream;
  final int? length;
  final String? filename;
  final String mimeType;

  GLUpload({
    required this.stream,
    this.length,
    this.filename,
    this.mimeType = 'application/octet-stream',
  });

  factory GLUpload.fromBytes(
    Uint8List bytes, {
    String? filename,
    String mimeType = 'application/octet-stream',
  }) {
    return GLUpload(
      stream: Stream.value(bytes),
      length: bytes.length,
      filename: filename,
      mimeType: mimeType,
    );
  }
}
""";



/// Emitted once in the client file — the default identity converter.
const dartUploadDefaultConverter = '''
/// Default converter — passes GLUpload through as-is.
/// The selected adapter's multipartCall handles GLUpload natively.
Object defaultUploadConverter(GLUpload upload) => upload;
''';

const javaUploadProgressCallback = '''
@FunctionalInterface
public interface UploadProgressCallback {
    void onProgress(long sent, long total);
}
''';

const javaGraphLinkMultipartAdapter = '''
public interface GraphLinkMultipartAdapter {
    String executeMultipart(String operations, String mapJson, Map<String, GLUpload> files, UploadProgressCallback onProgress) throws java.io.IOException;

    default String executeMultipart(String operations, String mapJson, Map<String, GLUpload> files) throws java.io.IOException {
        return executeMultipart(operations, mapJson, files, null);
    }
}
''';

const javaGLUpload = '''
public final class GLUpload {

    private final InputStream stream;
    private final long length;
    private final String filename;
    private final String mimeType;

    public GLUpload(InputStream stream, long length, String filename, String mimeType) {
        this.stream = stream;
        this.length = length;
        this.filename = filename;
        this.mimeType = mimeType;
    }

    public GLUpload(InputStream stream, long length, String filename) {
        this(stream, length, filename, "application/octet-stream");
    }

    public static GLUpload fromBytes(byte[] bytes, String filename, String mimeType) {
        return new GLUpload(new ByteArrayInputStream(bytes), bytes.length, filename, mimeType);
    }

    public static GLUpload fromBytes(byte[] bytes, String filename) {
        return fromBytes(bytes, filename, "application/octet-stream");
    }

    public static GLUpload fromFile(File file) throws IOException {
        return new GLUpload(new FileInputStream(file), file.length(), file.getName(), "application/octet-stream");
    }

    public static GLUpload fromFile(File file, String mimeType) throws IOException {
        return new GLUpload(new FileInputStream(file), file.length(), file.getName(), mimeType);
    }

    public InputStream getStream() { return stream; }
    public long getLength() { return length; }
    public String getFilename() { return filename; }
    public String getMimeType() { return mimeType; }
}
''';

