name: graphlink_dart_unions_interfaces
description: |
  GraphLink is a powerful code generation tool that generates type-safe client and server code from GraphQL schemas for Dart, Java, Spring Boot and more.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  graphlink:
    path: ../..
  http: ^1.2.0
  dio: ^5.9.2


