type Animal {
    name: String
}
type Owner {
    name: String
}

type Wrapper {
  id: ID!
}


type OwnerWithAnimal @glSkipOnServer(batch: false) {
    owner: Owner!
    animal: Animal
}


type Query {
    getOwnerWithAnimal: OwnerWithAnimal
}
