name: graphlink_java_cache_integration_tests
description: Java cache integration tests for GraphLink
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  graphlink:
    path: ../..
