// GENERATED CODE - DO NOT MODIFY BY HAND. ANY MODIFICATION WILL BE LOST ON NEXT GENERATION
// Generated by GraphLink dev
// GitHub: https://github.com/Oualitsen/graphlink
// Site: https://graphlink.dev
// Pub.dev https://pub.dev/packages/graphlink

declare module '../generated/context.js' {
  interface GraphLinkContext {
    // add your typed context fields here, for example:
    // userId?: string;
    // roles?: string[];
  }
}

