.PHONY: install generate start-server stop-server test ci kotlin

install:
	$(MAKE) -C typescript install

generate:
	$(MAKE) -C typescript generate

start-server:
	$(MAKE) -C typescript start-server

stop-server:
	$(MAKE) -C typescript stop-server

test:
	$(MAKE) -C typescript test

ci:
	$(MAKE) -C typescript ci

kotlin:
	$(MAKE) -C kotlin ci