enum GLTokenType {
  // Punctuation
  openBrace,
  closeBrace,
  openParen,
  closeParen,
  openBracket,
  closeBracket,
  colon,
  bang,
  equals,
  pipe,
  at,
  amp,
  spread, // '...'

  // Keywords (resolved from identifiers via lookup table)
  kwType,
  kwInput,
  kwInterface,
  kwEnum,
  kwScalar,
  kwUnion,
  kwDirective,
  kwFragment,
  kwQuery,
  kwMutation,
  kwSubscription,
  kwExtend,
  kwSchema,
  kwOn,
  kwImplements,
  kwRepeatable,
  kwTrue,
  kwFalse,
  kwNull,

  // Literals
  identifier,
  string,
  blockString,
  int_,
  float_,

  eof,
}

const Map<GLTokenType, String> tokenTypeNames = {
  GLTokenType.openBrace: "'{'",
  GLTokenType.closeBrace: "'}'",
  GLTokenType.openParen: "'('",
  GLTokenType.closeParen: "')'",
  GLTokenType.openBracket: "'['",
  GLTokenType.closeBracket: "']'",
  GLTokenType.colon: "':'",
  GLTokenType.bang: "'!'",
  GLTokenType.equals: "'='",
  GLTokenType.pipe: "'|'",
  GLTokenType.at: "'@'",
  GLTokenType.amp: "'&'",
  GLTokenType.spread: "'...'",
  GLTokenType.kwType: "'type'",
  GLTokenType.kwInput: "'input'",
  GLTokenType.kwInterface: "'interface'",
  GLTokenType.kwEnum: "'enum'",
  GLTokenType.kwScalar: "'scalar'",
  GLTokenType.kwUnion: "'union'",
  GLTokenType.kwDirective: "'directive'",
  GLTokenType.kwFragment: "'fragment'",
  GLTokenType.kwQuery: "'query'",
  GLTokenType.kwMutation: "'mutation'",
  GLTokenType.kwSubscription: "'subscription'",
  GLTokenType.kwExtend: "'extend'",
  GLTokenType.kwSchema: "'schema'",
  GLTokenType.kwOn: "'on'",
  GLTokenType.kwImplements: "'implements'",
  GLTokenType.kwRepeatable: "'repeatable'",
  GLTokenType.kwTrue: "'true'",
  GLTokenType.kwFalse: "'false'",
  GLTokenType.kwNull: "'null'",
  GLTokenType.identifier: 'identifier',
  GLTokenType.string: 'string',
  GLTokenType.blockString: 'block string',
  GLTokenType.int_: 'integer',
  GLTokenType.float_: 'float',
  GLTokenType.eof: 'end of file',
};

const Map<String, GLTokenType> keywords = {
  'type': GLTokenType.kwType,
  'input': GLTokenType.kwInput,
  'interface': GLTokenType.kwInterface,
  'enum': GLTokenType.kwEnum,
  'scalar': GLTokenType.kwScalar,
  'union': GLTokenType.kwUnion,
  'directive': GLTokenType.kwDirective,
  'fragment': GLTokenType.kwFragment,
  'query': GLTokenType.kwQuery,
  'mutation': GLTokenType.kwMutation,
  'subscription': GLTokenType.kwSubscription,
  'extend': GLTokenType.kwExtend,
  'schema': GLTokenType.kwSchema,
  'on': GLTokenType.kwOn,
  'implements': GLTokenType.kwImplements,
  'repeatable': GLTokenType.kwRepeatable,
  'true': GLTokenType.kwTrue,
  'false': GLTokenType.kwFalse,
  'null': GLTokenType.kwNull,
};
